#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/src/SpeedtestCommand.php';

echo "WebSpeedReport started.\n";

$application = new Application();
$application->add(new speedtestCommand());

try {
    $application->run();
} catch (Exception $e) {
    echo $e->getMessage();
}
